<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
    <Compile Include="tokenizer.fs" />
    <Compile Include="parser.fs" />
    <Compile Include="ActivePatternParser.fs" />
  </ItemGroup>

</Project>
